#!/usr/bin/bash

# Description: Links dotfiles to home directory.

link_file() {
	local src="$1"
	local dest="$2"
	ln -sf "$src" "$dest"
	echo "Linked $dest"
}

dotfiles_in_base=()
dotfiles_in_config=()

for file in "${dotfiles_in_base[@]}"; do
	link_file "$HOME/dotfiles/$file" "$HOME/.$file"
done

for file in "${dotfiles_in_config[@]}"; do
	link_file "$HOME/dotfiles/$file" "$HOME/.config/$file"
done

echo "dotfiles linked!"
